### ISSUE TITLE
UX - Add Print / PDF generation

### ISSUE THREAD

**Issue by itmilos** [Code-for-Serbia/uplatnica#11]
Find suitable React library to generate PDF-s

**Comment by itmilos** [comment]
Based on user research this is very important

**Comment by MrGeminus** [comment]
@itmilos, I will try to do it this week.

**Comment by itmilos** [comment]
@MrGeminus looks good, I would add margin left to create space between buttons or change it to grid and add gap

**Comment by MrGeminus** [comment]
@itmilos Me too, but I thought that you might want to split that from this because it's more related to styling. I will try to update the solution this week.

**Comment by itmilos** [comment]
@MrGeminus indeed I already did it, please rebase master into your branch and then I will approve your pull request

**Comment by MrGeminus** [comment]
@itmilos Yeah, I saw that. Rebase is done.
