### ISSUE TITLE
Add ability to save Template

### ISSUE THREAD

**Issue by itmilos** [Code-for-Serbia/uplatnica#8]
Add button to save template, template should hold all into typed by user, user witch has template created should have interface to see previous templates. 

Data should be held in IndexedDB until later time when we add some server less option.

**Comment by ivanbkovacevic** [comment]
I would like to try this to solve next

**Comment by itmilos** [comment]
@ivanbkovacevic you are Welcome! 

Find out the best type of localhost storage to use. In my opinion, IndexedDB (https://web.dev/indexeddb/) offers a more advantageous solution compared to Window.localStorage (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage?retiredLocale=de).
